name: Deploy

# Trigger the workflow on push and 
# pull request events on the production branch
on:
  push:
    branches:
      - main
      
# Authenticate to the the server via ssh 
# and run our deployment script 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSHKEY }}
          script: |
            #!/bin/bash
            set -e

            echo "Deployment started ..."

            (php artisan down) || true

            git pull origin main

            composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader

            php artisan clear-compiled

            php artisan optimize

            npm run prod

            php artisan migrate --force

            php artisan up

            echo "Deployment finished!"
